### ISSUE TITLE
TaLK Convolutions

### ISSUE THREAD

**Issue by lioutasb** [Separius/awesome-fast-attention#3]
I'm the author of "Time-aware Large Kernel Convolutions" (https://arxiv.org/abs/2002.03184) which is an alternative method to self-attention with linear complexity published in ICML 2020. You can find the implementation here (https://github.com/lioutasb/TaLKConvolutions). Thanks a lot.

**Comment by Separius** [comment]
Thanks, I will add it as soon as possible (less than a week)
